In [1]:
import numpy as np


A = np.array([[2, 3, 1],
              [-1, 1, 0],
              [1, 2, -1]])

B = np.array([[1, 2, 1],
              [0, 1, 2],
              [3, 1, 1]])


AB = np.dot(A, B)
BA = np.dot(B, A)


C = AB - BA

# Виведення матриці C
print("Матриця C = AB - BA:")
print(C)


Матриця C = AB - BA:
[[ 4  1  9]
 [-2 -6  3]
 [-8 -9  2]]


In [2]:
import numpy as np

matrix = np.array([[-1, 2],
                   [0, 1]])

result_matrix = np.dot(matrix, matrix)

# Виведення результату
print("Оригінальна матриця:")
print(matrix)
print("\nМатриця, піднесена до другого степеня:")
print(result_matrix)


Оригінальна матриця:
[[-1  2]
 [ 0  1]]

Матриця, піднесена до другого степеня:
[[1 0]
 [0 1]]


In [3]:
import numpy as np

A = np.array([[5, 0, 2, 3],
              [4, 1, 5, 3],
              [3, 1, -1, 2]])

B = np.array([[6],
              [-2],
              [7],
              [4]])

result = np.dot(A, B)

print(result)


[[56]
 [69]
 [17]]


In [4]:
import numpy as np

matrix = np.array([[1, 5, -5],
                  [4, 0, 3],
                  [2, -10, 3]])

determinant = np.linalg.det(matrix)

print("Визначник матриці:")
print(determinant)


Визначник матриці:
200.0000000000001


In [5]:
import numpy as np


matrix = np.array([[2, 3, 4, 1],
                  [1, 2, 3, 4],
                  [3, 4, 1, 2],
                  [4, 1, 2, 3]])

determinant = np.linalg.det(matrix)


print("Визначник матриці:")
print(determinant)


Визначник матриці:
-160.00000000000009


In [6]:
import numpy as np

# Ваша матриця
matrix = np.array([[1, 1, 1, 1],
                  [1, 1, -1, -1],
                  [1, -1, 1, -1],
                  [1, -1, -1, 1]])

# Знаходження оберненої матриці
inverse_matrix = np.linalg.inv(matrix)

print("Обернена матриця:")
print(inverse_matrix)


Обернена матриця:
[[ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25 -0.25 -0.25]
 [ 0.25 -0.25  0.25 -0.25]
 [ 0.25 -0.25 -0.25  0.25]]


In [7]:
import numpy as np

matrix = np.array([[-2, 3, 1, -1],
                  [3, 2, 1, 4],
                  [1, 2, 3, 4],
                  [0, 2, 3, 3]])

num_rows, num_cols = matrix.shape

rank = min(num_rows, num_cols)


if not all(matrix[-1, :] == 0):
    for i in range(rank):
        max_val = abs(matrix[i, i])
        max_row = i
        for j in range(i + 1, num_rows):
            if abs(matrix[j, i]) > max_val:
                max_val = abs(matrix[j, i])
                max_row = j

        if max_val == 0:
            continue

        if max_row != i:
            matrix[[i, max_row]] = matrix[[max_row, i]]

        for j in range(i + 1, num_rows):
            factor = int(matrix[j, i] / matrix[i, i])  
            matrix[j, i:] -= factor * matrix[i, i]


for i in range(rank):
    if all(matrix[i, i:] == 0):
        rank = i
        break

num_cols = matrix.shape[1]

print("Ранг матриці: ", rank)


Ранг матриці:  3
